# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  docker: circleci/docker@2.6.0
workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
        cache_from: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
        image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
        tag: latest
