# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  docker: circleci/docker@2.6.0
workflows:
  build-push-docker-image:
    jobs:
      - docker/publish:
          resource_class: small
          filters: 
            tags:
              only: 
                - /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
          cache_from: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:latest
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: latest,$CIRCLE_TAG
